### ISSUE TITLE
UnknownClassException in Typo3 9

### ISSUE THREAD

**Issue by Bratwurster** [joppnet/jn_phpcontentelement#10]
Hello

sry for my bad english ;-)

i upgraded typo3 8>9 and jn_phpcontentelement to 1.1.9

in Typo3 8 all were fine

in Typo3 9 every page with php content shows this error:

(1/2) #1278450972 TYPO3\CMS\Extbase\Reflection\Exception\UnknownClassException
Class Joppnet\JnPhpcontentelement\Controller\Joppnet\JnPhpcontentelement\Controller\JnPhpContentControllerController does not exist. Reflection failed.

plugin ist activated and up2date

what cann i do?

thanx

Michael

**Comment by Bratwurster** [comment]
Does nobody has the same issue? I noticed the double ...ControllerController at the end, could it be because of that? How do i fix this?

**Comment by oliverschloebe** [comment]
Hi @Bratwurster, sorry for the late reply but I suggest you to downgrade to 1.1.6 as 1.1.8 and up wasn't supposed to support TYPO3 < 10.
