### ISSUE TITLE
Support for Typo3 v12

### ISSUE THREAD

**Issue by Typo3AndMore** [joppnet/jn_phpcontentelement#15]
I am using this extension for a long time. Now I want to upgrade to typo3 12.4.
Are there any plans to support Typo3 v12?
Thanks & greetings

**Comment by FrischeWelt** [comment]
Hi there, we are also using this usefull extension for some TYPO3 installations .... waiting for an ext. upgrade to fullfill these other TYPO3 Upgrades .... thanks a lot in advance for some kind of informations about your developement plans ... Frank

**Comment by tomleiter** [comment]
I would also be happy about an update to TYPO3 12

**Comment by oliverschloebe** [comment]
Just released version [1.3.0](https://github.com/joppnet/jn_phpcontentelement/tree/1.3.0) that's compatible with TYPO3 v12!

Happy Easter! 🐇

**Comment by Typo3AndMore** [comment]
Thank you very much. Good job!

**Comment by tomleiter** [comment]
Me Too... Thank you!

**Comment by FrischeWelt** [comment]
Thanx a lot for your work :-)
