### ISSUE TITLE
Use in TYPO3 v8

### ISSUE THREAD

**Issue by netzteil** [joppnet/jn_phpcontentelement#2]
I get an error, if i try to use more than one php-ce, saying class foo already registered:
the classes are named: user_wetter and user_wetterdetail. I tried to rename one class, with no effect

'Fatal error: Cannot declare class user_wetterdetail, because the name is already in use in /var/www/bad-aibling/typo3conf/ext/jn_phpcontentelement/Classes/Domain/Model/JnPHPContent.php(60) : eval()'d code on line 5'

Any reply will be greatly appreciated.

**Comment by OliverSchloebe** [comment]
Hi @netzteil, a common pattern is to wrap your class definition in `if( !class_exists('user_wetterdetail') ) { class user_wetterdetail ... }` which should fix your issue.

**Comment by netzteil** [comment]
Solved
