### ISSUE TITLE
Forms (Typo3 8)

### ISSUE THREAD

**Issue by dinhtamtr** [joppnet/jn_phpcontentelement#4]
Hello @oliverschloebe,

Thanks for the extension! Is there a way to make get and post forms work with the extension? I tried to make a get form, but it redirects to the root page instead of the page specified in the "action".

Thank you!

**Comment by oliverschloebe** [comment]
Hi dinhtamtr, may you please provide a code example here? Thanks!

**Comment by dinhtamtr** [comment]
Of course,

Here is a simple example:

`<?php

echo '<form action="" method="get">
  First name: <input type="text" name="fname"><br>
  Last name: <input type="text" name="lname"><br>
  <input type="submit" value="Submit">
</form>';

?>`

If this code is used in a subpage of a website, the submit button will redirect to the home page, instead of the page specified in the **_action_** tag

**Comment by oliverschloebe** [comment]
Can you tell me what your `action` URI looks like? If it's containing `GET` parameters, they wont be taking into effect in a `GET` form. That's quite usual behaviour.

**Comment by dinhtamtr** [comment]
I've tried the simple form a moment ago and the behavior seems normal. My more complex form exibits the problem however. I will investigate further and come back to you.

**Comment by oliverschloebe** [comment]
If the action parameter's URI includes GET parameters like `https://mydomain.com/?id=12` then the `GET` form will redirect to `https://mydomain.com/` after submitting. That's quite normal behaviour as mentioned earlier.

You'll have to include the URI's `GET` parameter as `<input type="hidden" ...` fields inside the `<form>...</form>` tags.

**Comment by dinhtamtr** [comment]
I found the issue,

I'm currently using the `realurl` extension, which replaces the id-based url to speaking urls. I used the id-based url in the form action, which redirected my form to the homepage instead of the current page. This issue was fixed when i used the url provided by `realurl`.

Example:
`https://mydomain.com/myform` would redirect to `https://mydomain.com/?name=test` instead of `https://mydomain.com/myform/?name=test` if `https://mydomain.com/?id=12` was used instead of `https://mydomain.com/myform` in the form action.


However, another issue arose. 

Given the following code:

```
<?php
  
if(isset($_GET['fname'])){
  echo $_GET['fname'];
};

echo '<form action="https://mydomain.com/myform" method="get">
  First name: <input type="text" name="fname"><br>
  Last name: <input type="text" name="lname"><br>
  <input type="submit" value="Submit">
</form>';

?>
```

`$_GET['fname']` do not seems to retrieve the data from the url, and is not echoed. This could also be caused by `realurl`, investigating further.

**Comment by oliverschloebe** [comment]
Try to `var_dump` the `$_GET` global first to see if it holds any data at all.

**Comment by dinhtamtr** [comment]
`var_dump($_GET);` returned `array(1) { ["id"]=> string(4) "6001" }`

Even tho the url shown is `https://mydomain.com/myform/?fname=test&lname=test`. This increasingly looks like an issue between this and `realurl`

**Comment by oliverschloebe** [comment]
I suppose `6001` reflects the page uid of the page `/myform/`, right? Really weird it doesn't seem to be aware of the other two `GET` parameters.

**Comment by dinhtamtr** [comment]
Yes `6001` is the page uid. Weird indeed, i'll investigate further and keep you informed.

**Comment by oliverschloebe** [comment]
Thank you!
