### ISSUE TITLE
List view issue after installation

### ISSUE THREAD

**Issue by iBros** [joppnet/jn_phpcontentelement#5]
After installation of the extension, I get this when going to List view.
```
Oops, an error occurred!
An exception occurred while executing 'SELECT ' uid' FROM
'tx_jnphpcontentelement_domain_model_jnphpcontent' WHERE
('tx_jnphpcontentelement_domain_model_jnphpcontenf .'pid' = 2251) AND
(('tx_jnphpcontentelement_domain_model_jnphpcontenf .'deleted' = 0) AND
(('tx_jnphpcontentelement_domain_model_jnphpcontenf .'t3ver_wsid' = 0) OR
('tx_jnphpcontentelement_domain_model_jnphpcontenf .'t3ver_state' <= 0)))': Table
'usr_p438205_1.tx_jnphpcontentelement_domain_model_jnphpcontent' doesn't exist
```

**Comment by oliverschloebe** [comment]
Hi @iBros, seems like the database table hasn't been created. Have you tried running a DB compare in the install tool (or `Analyze Database Structure` in TYPO3 v8 and up)? This should be creating all missing DB tables.

**Comment by iBros** [comment]
Hi @oliverschloebe Thanks for the info. I get another error when trying to do that. If the extension is not active, there are no errors.

Summary:
- I get an error when re-activating the extension (not on first install): `Oops, an error occurred!
Undefined class constant 'SIGNAL_PreFileCreate'` (but it is active afterwards)
- I get beforementioned error when going to List View
- I get an error when trying to use the DB check tool: `	
Oops, an error occurred!
Call to a member function getType() on null` (this goes away, as soon as the extension is deactivated)

I am not sure if this is specifically due to this extension or a general issue... Not too familiar with Typo3 I have to admit.

**Comment by oliverschloebe** [comment]
What TYPO3 version are you running?

**Comment by iBros** [comment]
8.7.9

**Comment by oliverschloebe** [comment]
Hi @iBros, may you please upgrade your TYPO3 installation to the most recent 8.7.x version available? This seems to be a bug in earlier versions of the 8.7.x branch and doesn't actually seem to be related to the `jn_phpcontentelement` extension: https://forge.typo3.org/issues/85548

Thank you!
