### ISSUE TITLE
Cache problem

### ISSUE THREAD

**Issue by baumkuchen84** [joppnet/jn_phpcontentelement#6]
hey there
dunno if this is an issue with the plugin or with my typo installation but I experience the following problem with a simple php script:

I'm trying to write a value from the global get array to some gobal variable but it seems that if I reload the page with a different value in the get array the value isn't updated. If I change the php script and save in the admin frontend and reload the page the value is grabbed correctly.

Page:
https://site.com/index.php?id=66&ref_id=1234

Code:
$v1 = $_GET["ref_id"]
echo $v1;

Generated page on first load:
Value correctly shown: 1234

--> Changing Value and loading page again https://site.com/index.php?id=66&ref_id=5678

Value shown: 1234

**Comment by oliverschloebe** [comment]
Hi @baumkuchen84, have you tried disabling the page cache on the page the plugin is inserted on in TYPO3?

**Comment by baumkuchen84** [comment]
> Hi @baumkuchen84, have you tried disabling the page cache on the page the plugin is inserted on in TYPO3?

No I haven't... Thanks! Doing so worked like a charm!
