### ISSUE TITLE
[feature-request] Parameters in plugin

### ISSUE THREAD

**Issue by DavidBruchmann** [joppnet/jn_phpcontentelement#7]
Having the script-record saved somewhere in the page-tree it would be nice being able to call each script with different parameters which can be set by the plugins. Then the plugins would optionally provide the parameters for the php-code.  
Being able to set the parameters also by TypoScript would be awesome, but surely that can be already programmed in the php-records - just it would be an individual solution and is a bit overhead if every record has to include the corresponding code.

**Comment by DavidBruchmann** [comment]
It would be enough to provide in the plugin an own field for php-code too and parse the one of the plugin and the record(s) as one script.

**Comment by oliverschloebe** [comment]
Hi, I get your point but what's wrong with adding additional PHP records including the custom parameters on a per page basis instead of adding the additional code to the plugin itself?

**Comment by DavidBruchmann** [comment]
Hi and thanks for your answer.  
Honestly I never thought about that possibility and haven't tested yet if everything is working fine then.  
Your argument would then even make my desire for the TypoScript-inclusion in so far superfluous as it had to be noted only once and could be included always then.  
The comfort is in my opinion a bit reduced without my proposition but don't feel obligated in any kind, because it turned out that the solution with your extension seems never being suitable for the customer and I'll probably never use it there.  
So for the moment I'll close the issue even without verification, I can open again if the situation is changing. Also a PR would be thinkable then.
